routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('category', 'CategoryController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;
    
    public function childs(){
        return $this->hasMany(Category::class, 'parent_id', 'id');
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::where('parent_id', 0)->get();
        $allCategories = [];
        $allCategories = $this->allCategoresName(Category::all()->toArray());
        // dd($allCategories);
        
        return view('category.index', compact('categories', 'allCategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $category = new Category;
        $request->validate([
            'name' => 'required|unique:categories'
        ]);

        $category->name = $request->name;
        $category->description = $request->description;
        $category->parent_id = $request->parent_id;
        $category->save();
        return response([
            'status'=> true,
            'data'=> $category->all()
        ], 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        if($id){
            return response($category, 200);
        }
        return response([]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
            $category = new Category;
            $category = $category->find($id);
            $request->validate([
                'uname' => 'required',

            ]);

            $category->name = $request->uname;
            $category->description = $request->udescription;
            $category->parent_id = $request->uparent_id;
            $category->save();
            return response([
                'status'=> true,
                'data'=> $category
            ], 200);
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(!empty($id)){
            $category = new Category;
            $category = $category->find($id)->delete();
            return response(['status'=>$category], 200);
        }

        
    }

    public function allCategoresName($allCategories){
        $categories = ['No Parent'];
        foreach($allCategories as $key => $value){
            $categories[$value['id']] = $value['name'];
        }
        return $categories;
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/category/childCategory.blade.php
<ul>
@foreach($childs as $key => $child)
	<li>
	    {{ $child->name }} <span><a class="text-primary edit" data-id="{{ $childs[$key]['id'] }}" href="Javascript:void(0);"><i class="fa fa-edit"></i></a> <a id="delete" class="text-danger delete" data-id="{{ $childs[$key]['id'] }}" href="Javascript:void(0);"><i class="fa fa-trash"></i></a></span>
	    @if(count($child->childs))
            @include('category.childCategory',['childs' => $child->childs])
        @endif
	</li>
@endforeach
</ul>

resources/views/category/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Manage Category 
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-primary float-right" data-toggle="modal" data-target="#categoryModal">
                    Add Category
                    </button>
                </div>

                <div class="card-body">
                    <div id="ajax-status"></div>
                    @forelse($categories as $category)
                        <ul>
                            <li>
                                {{ $category->name }} <span><a class="text-primary edit" data-id="{{ $category->id }}" href="Javascript:void(0);"><i class="fa fa-edit"></i></a> <a id="delete" class="text-danger delete" data-id="{{ $category->id }}" href="Javascript:void(0);"><i class="fa fa-trash"></i></a></span>
                                @if( count($category->childs) )
                                    <!-- @foreach( $category->childs as $subCategory )
                                        <ul>
                                            <li> {{ $subCategory->childs }} </li>
                                        </ul>
                                    @endforeach -->
                                    @include('category.childCategory', ['childs'=> $category->childs])
                                @endif
                            </li>
                        </ul>
                    @empty
                        No category found...!    
                    @endforelse
                </div>
            </div>
        </div>

        </div>
    </div>
</div>


<!-- Modal -->
<form method="POST" action="{{ route('category.store') }}" id="form">
<div class="modal fade" id="categoryModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
                @csrf
                <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>

                    <div class="col-md-6">
                        <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" autofocus>

                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="description" class="col-md-4 col-form-label text-md-right">Description</label>

                    <div class="col-md-6">
                        <textarea class="form-control" name="description" id="description"></textarea>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="parent_id" class="col-md-4 col-form-label text-md-right">Parent</label>

                    <div class="col-md-6">
                        <select class="form-control" name="parent_id" id="parent_id"> 
                            @foreach( $allCategories as $key => $value)
                                <option value="{{ $key }}">{{ $value }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" id="add-category" class="btn btn-primary actionBtn">Save changes</button>
      </div>
    </div>
  </div>
</div>
</form>

<form method="POST" action="" id="updateForm">
<div class="modal fade" id="updateCategoryModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Update Category</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
                @csrf
                <div class="form-group row">
                    <label for="uname" class="col-md-4 col-form-label text-md-right">Name</label>

                    <div class="col-md-6">
                        <input id="uname" type="text" class="form-control @error('uname') is-invalid @enderror" name="uname" value="{{ old('uname') }}" autofocus>

                        @error('uname')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="udescription" class="col-md-4 col-form-label text-md-right">Description</label>

                    <div class="col-md-6">
                        <textarea class="form-control" name="udescription" id="udescription"></textarea>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="uparent_id" class="col-md-4 col-form-label text-md-right">Parent</label>

                    <div class="col-md-6">
                        <select class="form-control" name="uparent_id" id="uparent_id"> 
                            @foreach( $allCategories as $key => $value)
                                <option value="{{ $key }}">{{ $value }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" id="updataCategory" class="btn btn-primary">Update changes</button>
      </div>
    </div>
  </div>
</div>
</form>
@endsection

@section('style')
    <style>
        p.alert.alert-sucess {
            margin: 0;
            padding: 0;
        }
    </style>
@endsection

@section('scripts')
    <script>
    window.onload = ()=> {
        $(document).ready(()=>{
            
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $('#add-category').on('click', (e)=>{
                const data = {
                    name: $('#name').val(),
                    description: $('#description').val(),
                    parent_id: $('#parent_id').val()
                    
                };
                
                e.preventDefault();
                
                const request = $.ajax({
                    url: `${ajaxURL}/category`,
                    method: 'POST',
                    dataType: 'json',
                    data: data,
                    beforeSend: ()=>{

                    },
                    success: (data)=>{
                        const cathtml = `<div class="alert alert-success">
                        <p class="alert alert-sucess">Category Added Successfully...</p>
                    </div>`;
                        $('#ajax-status').html(cathtml);
                        $('#categoryModal').modal('hide');
                        $("#form").trigger('reset');
                    },
                    error: (error)=>{
                        console.log(0);
                    }

                });
            });

            // for(i=0; i<=$('.edit').length; i++){
            //     console.log(i);
            //     $(i).on('click', (e)=>{
            //         console.log(i);
            //         console.log($(this).data("id"));
            //     });
            // }

            // $('.edit').map(function() {
            //     console.log($(this).data('id'));
            // });
            $('body').on('click', '.edit', function(e) {  
                console.log($(this).data('id'));
                const id = $(this).data('id');
                $('#updateCategoryModal').modal('show');
                e.preventDefault();
                $.ajax({
                    url: `${ajaxURL}/category/${id}/edit`,
                    method: 'GET',
                    dataType: 'json',
                    data: {},
                    success: (result)=>{
                        console.log(result);
                        // $('.actionBtn').attr('id', 'updateCatgory');
                        $('#updateCategoryModal #uname').val(result.name);
                        $('#updateCategoryModal #udescription').val(result.description);
                        // $('#updateCategoryModal #uparent_id').val(result.parent_id);
                        $(`#updateCategoryModal #uparent_id option[value=${result.parent_id}]`).attr('selected','selected');
                        update();
                        $('#updataCategory').on('click', (e)=>{
                            e.preventDefault();
                            $.ajax({
                                url: `/category/${id}`,
                                method: 'PUT',
                                dataType: 'json',
                                data: $('#updateForm').serialize(),
                                success: (result)=>{
                                    console.log(result)
                                },
                                error: (error)=>{
                                    console.log(error);
                                }
                            });
                        });
                    },
                    error: (error)=>{
                        console.log(error);
                    }
                });
            });

            $('body').on('click', '.delete', function(e) {  
                console.log($(this).data('id'));
                const id = $(this).data('id');
                $.ajax({
                    url: `${ajaxURL}/category/${id}`,
                    method: 'DELETE',
                    dataType: 'json',
                    data: {id: id},
                    success: (result)=>{
                        document.location.reload();
                    },
                    error: (error)=>{
                        console.log('delete error: ',error);
                    }
                });
            });

            function update(data){
                console.log(data);
            }

        });
    }

    </script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @yield('style')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>

    <script>
        const ajaxURL = 'http://localhost:8000';
    </script>
    @yield('scripts')
</body>
</html>